/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp ../connd/conn.xml -c ConnectionManagerInterface -p connectionamanagerinterface
 */

#include "connectionamanagerinterface.h"

/*
 * Implementation of interface class ConnectionManagerInterface
 */

ConnectionManagerInterface::ConnectionManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ConnectionManagerInterface::~ConnectionManagerInterface()
{
}

