/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ConnAdaptor -a connadaptor.h:connadaptor.cpp com.jolla.Connectiond.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "connadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ConnAdaptor
 */

ConnAdaptor::ConnAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ConnAdaptor::~ConnAdaptor()
{
    // destructor
}

void ConnAdaptor::sendConnectReply(const QString &in0, int in1)
{
    qDebug() << Q_FUNC_INFO << in0 << in1;
    // handle method call com.jolla.Connectiond.sendConnectReply
    QMetaObject::invokeMethod(parent(), "sendConnectReply", Q_ARG(QString, in0), Q_ARG(int, in1));
}

void ConnAdaptor::sendUserReply(const QVariantMap &input)
{
    qDebug() << Q_FUNC_INFO << input;
    // handle method call com.jolla.Connectiond.sendUserReply
    QMetaObject::invokeMethod(parent(), "sendUserReply", Q_ARG(QVariantMap, input));
}

