/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c ConnAdaptor -a connadaptor.h:connadaptor.cpp conn.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONNADAPTOR_H_1363752885
#define CONNADAPTOR_H_1363752885

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.jolla.Connectiond
 */
class ConnAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.jolla.Connectiond")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.jolla.Connectiond\">\n"
"    <signal name=\"connectionRequest\"/>\n"
"    <signal name=\"wlanConfigurationNeeded\"/>\n"
"    <signal name=\"errorReported\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"error\"/>\n"
"    </signal>\n"
"    <signal name=\"requestBrowser\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"url\"/>\n"
"    </signal>\n"
"    <signal name=\"userInputCanceled\"/>\n"
"    <signal name=\"userInputRequested\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"service\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"fields\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </signal>\n"
"    <signal name=\"connectionState\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"state\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"type\"/>\n"
"    </signal>\n"
"    <method name=\"sendConnectReply\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"in0\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"in1\"/>\n"
"    </method>\n"
"    <method name=\"sendUserReply\">\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"input\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"connectToType\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"in0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ConnAdaptor(QObject *parent);
    virtual ~ConnAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void connectToType(const QString &in0);
    void sendConnectReply(const QString &in0, int in1);
    void sendUserReply(const QVariantMap &input);
Q_SIGNALS: // SIGNALS
    void connectionRequest();
    void connectionState(const QString &state, const QString &type);
    void errorReported(const QString &error);
    void requestBrowser(const QString &url);
    void userInputCanceled();
    void userInputRequested(const QString &service, const QVariantMap &fields);
    void wlanConfigurationNeeded();
};

#endif
